.Dd November 4, 2019
.Dt WALK 1
.
.Sh NAME
.
.Nm walk
.Nd Walk a directory tree and print the name of every regular file.
.
.Sh SYNOPSIS
.
.Nm
.Op Ar path
.
.Sh DESCRIPTION
.
.Nm
traverses a directory hierarchy starting at
.Em path ,
which defaults to the current directory, and prints the name of
every regular file.
.Pp
It doesn't print the names of directories, and it skips directories
and files whose names start with a dot.
.
.Sh AUTHOR
.An Michel Martens Aq mail@soveran.com
